using System.Collections.Generic;

namespace DI.FM.ViewModel
{
    class ChannelsHelper
    {
        public static Dictionary<string, string[]> ChannelsAssets = new Dictionary<string, string[]>()
        {
            {"deeptech", new string[]{"ms-appx:///Assets/Channels/channel1.png", "#3a3a3a", "#c66a33"}},
            {"liquiddubstep", new string[]{"ms-appx:///Assets/Channels/channel2.png", "#2f203a", "#3874ab"}},
            {"glitchhop", new string[]{"ms-appx:///Assets/Channels/channel3.png", "#4ea1a1", "#00191a"}},
            {"darkdnb", new string[]{"ms-appx:///Assets/Channels/channel4.png", "#380e01", "#aa350b"}},
            {"classiceurodisco", new string[]{"ms-appx:///Assets/Channels/channel5.png", "#123c69", "#700c6b"}},
            {"trance", new string[]{"ms-appx:///Assets/Channels/channel6.png", "#22a0d2", "#0071ae"}},
            {"vocaltrance", new string[]{"ms-appx:///Assets/Channels/channel7.png", "#94ac2e", "#e03176"}},
            {"lounge", new string[]{"ms-appx:///Assets/Channels/channel8.png", "#009fc6", "#422d14"}},
            {"chillout", new string[]{"ms-appx:///Assets/Channels/channel9.png", "#01b4dd", "#0072aa"}},
            {"vocalchillout", new string[]{"ms-appx:///Assets/Channels/channel10.png", "#d06a00", "#24797e"}},
            {"house", new string[]{"ms-appx:///Assets/Channels/channel11.png", "#ff3f00", "#ffa300"}},
            {"progressive", new string[]{"ms-appx:///Assets/Channels/channel12.png", "#221238", "#7f0e98"}},
            {"minimal", new string[]{"ms-appx:///Assets/Channels/channel13.png", "#8da639", "#e2dd46"}},
            {"harddance", new string[]{"ms-appx:///Assets/Channels/channel14.png", "#e25300", "#fed362"}},
            {"eurodance", new string[]{"ms-appx:///Assets/Channels/channel15.png", "#fe6a00", "#ffeb00"}},
            {"electro", new string[]{"ms-appx:///Assets/Channels/channel16.png", "#da9fbb", "#c575b0"}},
            {"techhouse", new string[]{"ms-appx:///Assets/Channels/channel17.png", "#ffa100", "#a10e00"}},
            {"psychill", new string[]{"ms-appx:///Assets/Channels/channel18.png", "#1bbea1", "#3b31ee"}},
            {"goapsy", new string[]{"ms-appx:///Assets/Channels/channel19.png", "#d67c0b", "#2ee3df"}},
            {"progressivepsy", new string[]{"ms-appx:///Assets/Channels/channel20.png", "#032d46", "#5cc6dc"}},
            {"hardcore", new string[]{"ms-appx:///Assets/Channels/channel21.png", "#40a2c7", "#77c6eb"}},
            {"djmixes", new string[]{"ms-appx:///Assets/Channels/channel22.png", "#00313f", "#1fb6e8"}},
            {"ambient", new string[]{"ms-appx:///Assets/Channels/channel23.png", "#0f3645", "#3da5cc"}},
            {"drumandbass", new string[]{"ms-appx:///Assets/Channels/channel24.png", "#006262", "#434343"}},
            {"classictechno", new string[]{"ms-appx:///Assets/Channels/channel25.png", "#451e26", "#687871"}},
            {"epictrance", new string[]{"ms-appx:///Assets/Channels/channel26.png", "#1a8c03", "#00387b"}},
            {"ukgarage", new string[]{"ms-appx:///Assets/Channels/channel27.png", "#1a3db9", "#f70b0b"}},
            {"breaks", new string[]{"ms-appx:///Assets/Channels/channel28.png", "#9e3b09", "#ef580c"}},
            {"cosmicdowntempo", new string[]{"ms-appx:///Assets/Channels/channel29.png", "#296150", "#8fbf8d"}},
            {"techno", new string[]{"ms-appx:///Assets/Channels/channel30.png", "#007bc1", "#6dcaf2"}},
            {"soulfulhouse", new string[]{"ms-appx:///Assets/Channels/channel31.png", "#003244", "#36b0d7"}},
            {"deephouse", new string[]{"ms-appx:///Assets/Channels/channel32.png", "#41001e", "#e90069"}},
            {"tribalhouse", new string[]{"ms-appx:///Assets/Channels/channel33.png", "#3f0f0f", "#faa919"}},
            {"funkyhouse", new string[]{"ms-appx:///Assets/Channels/channel34.png", "#f1a1ba", "#e52e7e"}},
            {"deepnudisco", new string[]{"ms-appx:///Assets/Channels/channel35.png", "#ffd85e", "#ff916e"}},
            {"spacemusic", new string[]{"ms-appx:///Assets/Channels/channel36.png", "#003a94", "#5aa8d6"}},
            {"hardstyle", new string[]{"ms-appx:///Assets/Channels/channel37.png", "#a20013", "#da0019"}},
            {"chilloutdreams", new string[]{"ms-appx:///Assets/Channels/channel38.png", "#e23d1e", "#ef9f00"}},
            {"liquiddnb", new string[]{"ms-appx:///Assets/Channels/channel39.png", "#49c6f3", "#004881"}},
            {"classiceurodance", new string[]{"ms-appx:///Assets/Channels/channel40.png", "#180a0a", "#de1f25"}},
            {"handsup", new string[]{"ms-appx:///Assets/Channels/channel41.png", "#5a164f", "#c01b7b"}},
            {"club", new string[]{"ms-appx:///Assets/Channels/channel42.png", "#433c38", "#919091"}},
            {"classictrance", new string[]{"ms-appx:///Assets/Channels/channel43.png", "#aeafb2", "#5f6062"}},
            {"classicvocaltrance", new string[]{"ms-appx:///Assets/Channels/channel44.png", "#833507", "#d36c03"}},
            {"dubstep", new string[]{"ms-appx:///Assets/Channels/channel45.png", "#bf1600", "#590b00"}},
            {"clubdubstep", new string[]{"ms-appx:///Assets/Channels/channel46.png", "#002496", "#019f7e"}},
            {"discohouse", new string[]{"ms-appx:///Assets/Channels/channel47.png", "#e9579e", "#010303"}},
            {"futuresynthpop", new string[]{"ms-appx:///Assets/Channels/channel48.png", "#e66c1f", "#fcb016"}},
            {"latinhouse", new string[]{"ms-appx:///Assets/Channels/channel49.png", "#da117c", "#f5b92b"}},
            {"oldschoolacid", new string[]{"ms-appx:///Assets/Channels/channel50.png", "#226576", "#f8c000"}},
            {"chiptunes", new string[]{"ms-appx:///Assets/Channels/channel51.png", "#083147", "#4a96b0"}},
        };
    }
}
